
spring:
    profiles:
      active:
        - dev
---
server:
  port: 8001 #注册中心占用8001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: micriservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2：
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
        
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.bxxmq.springcloud.entities
    mapper-locations: 
    - classpath:mybatis/mapper/**/*.xml
       
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
    app.nam: bxxmq-micriservicecloud-springcloudconfig01
    company.name: www.bxxmq.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$
    
---
    
server:
  port: 8002 #注册中心占用8002端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: micriservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2：
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
        
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.bxxmq.springcloud.entities
    mapper-locations: 
    - classpath:mybatis/mapper/**/*.xml
       
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
    app.nam: bxxmq-micriservicecloud-springcloudconfig02
    company.name: www.bxxmq.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$